apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-batch-engine
  namespace: feast-spark
data:
  config: |
    type: spark_application
    image: quay.io/aniket-redhat/feast-spark-driver:byos-spark-e2e-v9
    namespace: feast-spark
    service_account: feast-spark-driver
    executor_instances: 5
    executor_cores: 1
    executor_memory: "1g"
    driver_cores: 1
    driver_memory: "1g"
    concurrency: 10
    spark_version: "4.0.1"
