apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: spark-e2e
  namespace: feast-spark
spec:
  feastProject: feast_spark_postgres_e2e
  feastProjectDir:
    git:
      featureRepoPath: feature_repo
      ref: byos-spark-postgres
      url: 'https://github.com/aniketpalu/feast_examples.git'
  services:
    # v1 only (PR #6598). Not present on v1alpha1 schema.
    initImage: quay.io/aniket-redhat/feast-spark-driver:byos-spark-e2e-v6
    onlineStore:
      persistence:
        store:
          secretRef:
            name: redis-config
          type: redis
      server:
        image: quay.io/aniket-redhat/feast-spark-driver:byos-spark-e2e-v6
    offlineStore:
      persistence:
        store:
          secretRef:
            name: postgres-offline-config
          type: postgres
      server:
        image: quay.io/aniket-redhat/feast-spark-driver:byos-spark-e2e-v6
    registry:
      local:
        persistence:
          store:
            secretRef:
              name: postgres-registry-config
            type: sql
        server:
          image: quay.io/aniket-redhat/feast-spark-driver:byos-spark-e2e-v6
          restAPI: true
  batchEngine:
    configMapRef:
      name: spark-batch-engine
